version: '3'

services:
  qbittorrentvpn:
    restart: always
    image: dyonr/qbittorrentvpn
    container_name: qbittorrentvpn
    environment:
      - VPN_ENABLED=yes
      - VPN_TYPE=openvpn
      - NAME_SERVERS=1.1.1.1,1.0.0.1
      - LEGACY_IPTABLES=yes
      - LAN_NETWORK=192.168.1.0/24
      - PUID=1000
      - PGID=100
    ports:
      - 8082:8080
    volumes:
      - ${CONFIG_PATH}/qBittorrent/:/config
      - ${DOWNLOADS_PATH}/:/downloads
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
  
  jackett:
    restart: always
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=100
    ports:
      - 9117:9117
    volumes:
      - ${CONFIG_PATH}/Jackett/:/config
      - ${DOWNLOADS_PATH}/:/downloads
      - /etc/localtime:/etc/localtime:ro
  
  flaresolverr:
    restart: always
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - PUID=1000
      - PGID=100
    ports:
      - 8191:8191
    volumes:
      - /etc/localtime:/etc/localtime:ro
  
  sonarr:
    restart: always
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=100
    ports:
      - 8989:8989
    volumes:
      - ${CONFIG_PATH}/Sonarr/:/config
      - ${MEDIA_PATH}/TV/:/tv
      - ${DOWNLOADS_PATH}/:/downloads
      - /etc/localtime:/etc/localtime:ro
  
  radarr:
    restart: always
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=100
    ports:
      - 7878:7878
    volumes:
      - ${CONFIG_PATH}/Radarr/:/config
      - ${MEDIA_PATH}/Movie/:/movies
      - ${DOWNLOADS_PATH}/:/downloads
      - /etc/localtime:/etc/localtime:ro

  bazarr:
    restart: always
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=100
    ports:
      - 6767:6767
    volumes:
      - ${CONFIG_PATH}/Bazarr/:/config
      - ${MEDIA_PATH}/Movie/:/movies
      - ${MEDIA_PATH}/TV/:/tv
      - /etc/localtime:/etc/localtime:ro